# Generated by Django 4.1.7 on 2023-03-17 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_comment_post_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
