categories = [
    ('Prayer', 'Prayer'),
    ('Purpose', 'Purpose'),
    ('Vision', 'Vision'),
    ('Potentials', 'Potentials'),
    ('Spiritual Growth', 'Spiritual Growth'),
    ('Holyspirit', 'Holyspirit'),
    ('Leadership', 'Leadership'),
    ('Marriage', 'Marriage'),
    ('Faith', 'Faith'),
    ('Power', 'Power'),
    ('Dominion', 'Dominion'),
    ('Hearing from God', 'Hearing from God'),
    ('Personal Development', 'Personal Development'),
    ('Angels', 'Angels'),
    ('Bible Characters/Commenteries', 'Bible Characters/Commenteries'),
    ('Biography/Autography', 'Biography/Autography'),
    ('Blessing', 'Blessing'),
    ('Character', 'Character'),
    ('Emotions', 'Emotions'),
    ('Discipleship', 'Discipleship'),
    ('Deliverance', 'Deliverance'),
    ('Demons', 'Demons'),
    ('Endtime and Rapture', 'Endtime and Rapture'),
    ('Women', 'Women'),
    ('Wisdom', 'Wisdom'),
    ('Youth', 'Youth'),
    ('Evangelism', 'Evangelism'),
    ('Soul Winning', 'Soul Winning'),
    ('Fear', 'Fear'),
    ('Prosperity', 'Prosperity'),
    ('Money', 'Money'),
    ('Forgiveness', 'Forgiveness'),
    ('Word', 'Word'),
    ('Grace', 'Grace'),
    ('Healing', 'Healing'),
    ('Holiness', 'Holiness'),
    ('Lifestyle', 'Lifestyle'),
    ('Mind', 'Mind'),
    ('Men', 'Men'),
    ('Ministry', 'Ministry'),
    ('Miracle', 'Miracle'),
    ('Obedience', 'Obedience'),
    ('Peace', 'Peace'),
    ('Patience', 'Patience'),
    ('Worship', 'Worship'),
    ('Prophecy', 'Prophecy'),
    ('Revival', 'Rivival'),
    ('Mystery', 'Mystery')
]