# Generated by Django 4.1.7 on 2023-03-17 14:48

from django.db import migrations, models
import witness.models


class Migration(migrations.Migration):
    dependencies = [
        ("witness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorprofile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="viewerprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="editorprofile",
            name="bio",
            field=models.TextField(default="Jesus loves me!"),
        ),
        migrations.AddField(
            model_name="editorprofile",
            name="picture",
            field=models.ImageField(
                default="profiles/default.png",
                upload_to=witness.models.profile_image_path,
            ),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="bio",
            field=models.TextField(default="Jesus loves me!"),
        ),
        migrations.AddField(
            model_name="viewerprofile",
            name="picture",
            field=models.ImageField(
                default="profiles/default.png",
                upload_to=witness.models.profile_image_path,
            ),
        ),
    ]
